name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # إصدار مستقر يضمن التشغيل الصحيح

    - name: Publish
      run: dotnet publish -c Release -o release

    - name: Fix paths for GitHub Pages
      run: |
        sed -i 's/<base href="\/" \/>/<base href="\/nawaf-appointments\/" \/>/g' release/wwwroot/index.html
        touch release/wwwroot/.nojekyll

    - name: Upload to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot
        branch: gh-pages